hydra:
  run:
    dir: ./src/task/EXP0014_GenFactorRepr/outputs/${now:%Y-%m-%d}/${exp_name}/${now:%H-%M-%S}

defaults:
  - v1_nogenfactors
  - _self_

gen_factorset:
  - name: LSI
    args:
      depth_levels: 4
      ip_window: 5
      lsi_window: 10
  - name: LSI
    args:
      depth_levels: 5
      ip_window: 10
      lsi_window: 5
  - name: LSI
    args:
      depth_levels: 2
      ip_window: 5
      lsi_window: 20
  - name: LSI
    args:
      depth_levels: 3
      ip_window: 10
      lsi_window: 5
