hydra:
  run:
    dir: ./src/task/EXP0014_GenFactorRepr/outputs/${now:%Y-%m-%d}/${exp_name}/${now:%H-%M-%S}

defaults:
  - v3_lastv4_nogenfactors
  - _self_

gen_factorset:
  - name: CPI
    args:
      smoothing_window: 5
  - name: CPI
    args:
      smoothing_window: 10
  - name: CPI
    args:
      smoothing_window: 1
  - name: CPI
    args:
      smoothing_window: 10
