hydra:
  run:
    dir: ./src/task/EXP0016_SplitStrategy/outputs/${now:%Y-%m-%d}/${exp_name}/${now:%H-%M-%S}

defaults:
  - _self_

exp_name: ???

data_fp: data/preprocessed_jh/v7_factor_factory_rev1.parquet
ta_factorset_fp: src/task/EXP0016_SplitStrategy/external/results/factorset/5e273fc1.pt
regime_label_fp: /data/jh/repo/trading-lab/src/task/EXP0016_SplitStrategy/notebook/regime_label_v1.parquet

train_date_range: ???
valid_date_range: ???
test_date_range: ???

resample_rule: 5min

repr_lookback_num: 100
repr_lookahead_num: 24

regime_input_cols: [["foreign_trade", "close"], ["individual_trade", "close"], ["institutional_trade", "close"]]
regime_lookback_num: 50
regime_num_classes: 7

initial_balance: 1000000000

signal_stop_trade_after_n_min: 180
signal_trade_between_hours: null

# signal_label_type: sharpe_to_eod
signal_label_type: sharpe_to_180


input_dim: ???

gen_factorset: []

datamodule:
  name: basic_datamodule
  args:
    batch_size: 256
    num_workers: 4

    dataset:
      name: basic_dataset
      args: 
        regime_label_fp: ${regime_label_fp}
        regime_distance_threshold: 35
        regime_input_cols: ${regime_input_cols}
        regime_lookback_num: ${regime_lookback_num}
        data_fp: ${data_fp}
        ta_factorset_fp: ${ta_factorset_fp}
        gen_factorset: ${gen_factorset}
        train_date_range: ${train_date_range}
        valid_date_range: ${valid_date_range}
        test_date_range: ${test_date_range}
        repr_lookback_num: ${repr_lookback_num}
        repr_lookahead_num: ${repr_lookahead_num}
        signal_stop_trade_after_n_min: ${signal_stop_trade_after_n_min}
        signal_trade_between_hours: ${signal_trade_between_hours}
        resample_rule: ${resample_rule}
        soft_label_hold_thresh: 0.5
        soft_label_tau: 2.5
        soft_label_mode: dynamic
        signal_label_type: ${signal_label_type}
  
repr:
  model:
    name: repr_model
    args:
      network:
        name: repr_dlinear
        args:
          repr_lookback_num: ${repr_lookback_num}
          repr_lookahead_num: ${repr_lookahead_num}
          moving_avg_kernel_size: 25
      lr: 1e-3
      optimizer: Adam
      loss_func:
        name: l1
        args: {}
      

  callbacks: {}

  trainer:
    args:
      check_val_every_n_epoch: 1
      log_every_n_steps: 5
      max_epochs: 10

regime:
  model:
    name: regime_model
    args:
      network:
        name: regime_classifier
        args:
          regime_lookback_num: ${regime_lookback_num}
          regime_input_cols_num: ${len:${regime_input_cols}}
          num_classes: ${regime_num_classes}
      lr: 1e-3
      optimizer: Adam
      loss_func:
        name: cross_entropy
        args: {}
      num_classes: ${regime_num_classes}
      

  callbacks: {}

  trainer:
    args:
      check_val_every_n_epoch: 1
      log_every_n_steps: 5
      max_epochs: 60

signal:
  model:
    name: signal_model
    args:
      network:
        name: signal_mlpdropout
        args:
          input_dim: ${input_dim}
          repr_lookahead_num: ${repr_lookahead_num}
          output_dim: 3
          dropout_rate: 0.3
      lr: 1e-3
      optimizer: ASAM
      loss_func:
        name: reversefocal
        args: {}
      mixup_alpha: 1.0

  callbacks:
    - name: backtester
      args:
        initial_balance: ${initial_balance}
        train_date_range: ${train_date_range}
        valid_date_range: ${valid_date_range}
        test_date_range: ${test_date_range}
        df_save_col: [[backtest, net_pnl]]
        backtester:
          name: basic
          args:
            stop_loss_func:
              name: no_stop
              args: {}
            take_profit_func:
              name: no_take
              args: {}
            initial_balance: ${initial_balance}
            pred_to_signal_mode: shl_wsum
            position_size_strategy: voladj
            signal_threshold: 0.0
            risk_exposure: 0.2
            volatility_coef: 100
            volatility_window: 50
            volatility_clip_range: [0.1, 10]
            signal_stop_trade_after_n_min: ${signal_stop_trade_after_n_min}
            signal_trade_between_hours: ${signal_trade_between_hours}

  trainer:
    args:
      check_val_every_n_epoch: 4
      log_every_n_steps: 5
      max_epochs: 48