hydra:
  run:
    dir: ./src/task/EXP0014_GenFactorRepr/outputs/${now:%Y-%m-%d}/${exp_name}/${now:%H-%M-%S}

defaults:
  - v3_lastv4_nogenfactors
  - _self_

gen_factorset:
  - name: VSHPI
    args:
      ma_window: 1
      normalize_iv_gap: True
      openint_weight: 0.5
      skew_weight: 0.7
      vanna_weight: 0.5
  - name: VSHPI
    args:
      ma_window: 50
      normalize_iv_gap: True
      openint_weight: 0.5
      skew_weight: 0.5
      vanna_weight: 1.0
  - name: VSHPI
    args:
      ma_window: 50
      normalize_iv_gap: True
      openint_weight: 0.3
      skew_weight: 0.3
      vanna_weight: 0.5
  - name: VSHPI
    args:
      ma_window: 20
      normalize_iv_gap: True
      openint_weight: 0.3
      skew_weight: 0.3
      vanna_weight: 1.0
