hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/EXP0007/${now:%H-%M-%S}_${exp_name}

defaults:
  - _self_

exp_name: ???
desc: > 


data_fp: data/preprocessed_jh/v5-2.parquet
resample_rule: 5min

input_columns:
  - future_price_open
  - future_price_high
  - future_price_low
  - future_price_close
lookback_num: 12
lookahead_num: 12

model:
  name: STReLUpstream
  checkpoint_fp: null
  args:
    network:
      name: STReLUpstreamNonlinear
      args:
        input_ch: ${len:${input_columns}}
        hidden_dim: 512
        lookback_num: ${lookback_num}
        lookahead_num: ${lookahead_num}
        moving_avg_kernel_size: 3  # Consider not using SeriesDecompose
    lr: 1e-3
    regr_loss_func:
      name: L1
      args: {}
    clsf_loss_func:
      name: MSE # TODO: change into real classification loss
      args: {}
    reco_loss_func:
      name: MSE
      args: {}
    rank_loss_func:
      name: PairwiseMarginRanking
      args: {}
      
datamodule:
  name: STReL
  args:
    train_batch_size: 256
    train_num_workers: 48
    val_batch_size: 256
    val_num_workers: 48

    train_dataset:
      name: STReLUpstream
      args: &dataset_args
        data_fp: ${data_fp}
        resample_rule: ${resample_rule}
        date_range: [2015-01-01, 2018-12-31]
        input_columns: ${input_columns}
        lookback_num: ${lookback_num}
        lookahead_num: ${lookahead_num}

    val_dataset:
      name: STReLUpstream
      args:
        <<: *dataset_args
        date_range: [2019-01-01, 2020-12-31]


callback: []

trainer:
  args:
    check_val_every_n_epoch: 4
    log_every_n_steps: 10