hydra:
  run:
    dir: ./src/task/EXP0013_FactorFactory/outputs/${now:%Y-%m-%d}/${exp_name}/${now:%H-%M-%S}

defaults:
  - _self_

exp_name: ???

data_fp: data/preprocessed_jh/v6_factor_factory_rev1.parquet
factorset_fp: src/task/EXP0013_FactorFactory/external/results/factorset/000a54a0.pt

resample_rule: 5min
lookback_num: 1
initial_balance: 1000000000
stop_trade_after_n_min: 180


model:
  name: mixup
  args:
    mixup_alpha: 1.0
    network:
      name: mlp_dropout
      args:
        input_dim: 16
        output_dim: 3
        dropout_rate: 0.3
        lookback_num: ${lookback_num}
    lr: 1e-3
    optimizer: ASAM
    lr_scheduler: None
    loss_func:
      name: reversefocal
      args: {}
      
datamodule:
  name: basic
  args:
    batch_size: 256
    num_workers: 8

    dataset:
      name: basic
      args: 
        data_fp: ${data_fp}
        factorset_fp: ${factorset_fp}
        resample_rule: ${resample_rule}
        train_date_range: [2015-01-01, 2018-12-31]
        total_date_range: [2015-01-01, 2024-12-31]
        stop_trade_after_n_min: ${stop_trade_after_n_min}
        lookback_num: ${lookback_num}
        hold_thresh: 0.5
        tau: 2.5

callback:
  - name: backtester
    args:
      initial_balance: ${initial_balance}
      backtester:
        name: basic
        args:
          stop_loss_func:
            name: no_stop
            args: {}
          take_profit_func:
            name: no_take
            args: {}
          initial_balance: ${initial_balance}
          pred_to_signal_mode: shl_wsum
          position_size_strategy: voladj
          signal_threshold: 0.2
          risk_exposure: 0.2
          volatility_coef: 100
          volatility_window: 50
          volatility_clip_range: [0.1, 10]
          stop_trade_after_n_min: ${stop_trade_after_n_min}

trainer:
  args:
    check_val_every_n_epoch: 4
    log_every_n_steps: 5
    max_epochs: 48