hydra:
  run:
    dir: ./src/task/EXP0014_GenFactorRepr/outputs/${now:%Y-%m-%d}/${exp_name}/${now:%H-%M-%S}

defaults:
  - v3_lastv4_nogenfactors
  - _self_

gen_factorset:
  - name: RSSkew
    args:
      skew_window: 10
      norm_window: 60
  - name: RSSkew
    args:
      skew_window: 20
      norm_window: 30
  - name: RSSkew
    args:
      skew_window: 5
      norm_window: 60
  - name: RSSkew
    args:
      skew_window: 10
      norm_window: 10
