hydra:
  run:
    dir: ./src/task/EXP0014_GenFactorRepr/outputs/${now:%Y-%m-%d}/${exp_name}/${now:%H-%M-%S}

defaults:
  - v3_lastv4_nogenfactors
  - _self_

gen_factorset:
  - name: PLDI
    args:
      price_window: 1
      liquidity_window: 24
  - name: PLDI
    args:
      price_window: 20
      liquidity_window: 24
  - name: PLDI
    args:
      price_window: 30
      liquidity_window: 24
  - name: PLDI
    args:
      price_window: 20
      liquidity_window: 12
