defaults:
  - v1
  - _self_

desc: > 
  non-linear

model:
  name: ReprExtremaDetector
  args:
    network:
      name: ReprExtremaDetectorV2
      args:
        input_ch: 384
        hidden_dim: 1024
        output_num: 3
        moving_avg_kernel_size: 25
        input_lookback_num: ${input_lookback_num}
    lr: 1e-4
    loss_func:
      name: Focal
      args: {}