hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/EXP0009/${now:%H-%M-%S}_${exp_name}

defaults:
  - v1
  - _self_

model:
  name: basic
  args:
    network:
      name: nonlinear_maxpool
      args:
        input_ch: 10     # fixed for raw_price, ema_{5, 20, 60, 120}, date_token
        hidden_dim: 32
        lookback_num: ${lookback_num}
        num_outputs: 8    # fixed for 9 pivot zones
        moving_avg_kernel_size: 25
      